version: '3.9'
services:
  eureka-service:
    build: eureka-service
    container_name: eureka-service
    ports:
      - "8761:8761"
    networks:
      - backend
    healthcheck:
      test: [ "CMD", "curl", "http://eureka-service:8761/eureka" ]
      interval: 10s
      retries: 5
      timeout: 10s

  company-service:
    build: company-service
    container_name: company-service
    ports:
      - "8081:8081"
    networks:
      - backend
    depends_on:
      eureka-service:
        condition: service_healthy
      company-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://company-db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=mywords

  company-db:
    image: postgres:14-alpine
    container_name: company-db
    ports:
      - "6542:5432"
    networks:
      - backend
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mywords
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U habrpguser -d habrdb" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  laboratory-qc-service:
    build: laboratory-qc-service
    container_name: laboratory-qc-service
    ports:
      - "8082:8082"
    networks:
      - backend
    depends_on:
      eureka-service:
        condition: service_healthy
      laboratory-qc-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://laboratory-qc-db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=mywords

  laboratory-qc-db:
    image: postgres:14-alpine
    container_name: laboratory-qc-db
    ports:
      - "6543:5432"
    networks:
      - backend
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mywords
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U habrpguser -d habrdb" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  equipment-service:
    build: equipment-service
    container_name: equipment-service
    ports:
      - "8083:8083"
    networks:
      - backend
    depends_on:
      equipment-db:
        condition: service_healthy
      eureka-service:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://equipment-db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=mywords

  equipment-db:
    image: postgres:14-alpine
    container_name: equipment-db
    ports:
      - "6544:5432"
    networks:
      - backend
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mywords
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U habrpguser -d habrdb" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  measurement-service:
    build: measurement-service
    container_name: measurement-service
    ports:
      - "8084:8084"
    networks:
      - backend
    depends_on:
      measurement-db:
        condition: service_healthy
      eureka-service:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://measurement-db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=mywords

  measurement-db:
    image: postgres:14-alpine
    container_name: measurement-db
    ports:
      - "6545:5432"
    networks:
      - backend
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mywords
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U habrpguser -d habrdb" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  document-service:
    build: document-service
    container_name: document-service
    ports:
      - "8085:8085"
    networks:
      - backend
    depends_on:
      document-db:
        condition: service_healthy
      eureka-service:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://document-db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=mywords

  document-db:
    image: postgres:14-alpine
    container_name: document-db
    ports:
      - "6546:5432"
    networks:
      - backend
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mywords
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U habrpguser -d habrdb" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  gateway-service:
    build: gateway-service
    container_name: gateway-service
    ports:
      - "8080:8080"
    networks:
      - backend
    depends_on:
      eureka-service:
        condition: service_healthy

networks:
  backend:
    driver: bridge