CREATE TABLE IF NOT EXISTS STRUCTURE_ORGANIZATION
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    branch_id             BIGINT                                  NOT NULL,
    branch                VARCHAR                                 NOT NULL,
    department_id         BIGINT                                  NOT NULL,
    department            VARCHAR                                 NOT NULL,
    heat_supply_source_id BIGINT                                  NOT NULL,
    heat_supply_source    VARCHAR                                 NOT NULL,
    heat_supply_site_id   BIGINT,
    heat_supply_site      VARCHAR,
    technical_device_id   BIGINT,
    technical_device      VARCHAR,
    CONSTRAINT pk_structureOrganization PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS EQUIPMENT_UNITS
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    equipment_library_id BIGINT                                  NOT NULL,
    full_name            VARCHAR                                 NOT NULL,
    stationary_number    INTEGER,
    room                 VARCHAR,
    geodesy_locations    INTEGER,
    date_commissioning   DATE,
    period_stabilization INTEGER,
    diameter             INTEGER,
    length               INTEGER,
    height               INTEGER,
    width                INTEGER,
    dimensions           VARCHAR,
    structure_id         BIGINT                                  NOT NULL,
    CONSTRAINT pk_equipmentUnit PRIMARY KEY (id),
    CONSTRAINT FK_EQUIPMENT_UNITS_ON_STRUCTURE_ORGANIZATION
        FOREIGN KEY (structure_id) REFERENCES structure_organization (id)
);

CREATE TABLE IF NOT EXISTS ELEMENTS
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    element_library_id BIGINT                                  NOT NULL,
    element_name       VARCHAR                                 NOT NULL,
    standard_size      VARCHAR,
    thickness          DOUBLE PRECISION,
    min_diameter       INTEGER,
    min_thickness      DOUBLE PRECISION,
    max_diameter       INTEGER,
    max_thickness      DOUBLE PRECISION,
    equipment_id       BIGINT                                  NOT NULL,
    CONSTRAINT pk_element PRIMARY KEY (id),
    CONSTRAINT FK_ELEMENTS_ON_EQUIPMENT_UNITS FOREIGN KEY (equipment_id) REFERENCES equipment_units (id)
);

CREATE TABLE IF NOT EXISTS EQUIPMENT_PARTS_ELEMENTS
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    part_element_library_id BIGINT                                  NOT NULL,
    part_element_name       VARCHAR                                 NOT NULL,
    standard_size           VARCHAR,
    thickness               DOUBLE PRECISION,
    min_diameter            INTEGER,
    min_thickness           DOUBLE PRECISION,
    max_diameter            INTEGER,
    max_thickness           DOUBLE PRECISION,
    element_id              BIGINT                                  NOT NULL,
    CONSTRAINT pk_equipmentPartElement PRIMARY KEY (id),
    CONSTRAINT FK_EQUIPMENT_PARTS_ELEMENTS_ON_EQUIPMENT_ELEMENTS
        FOREIGN KEY (element_id) REFERENCES elements (id)
);