CREATE TABLE IF NOT EXISTS ORGANIZATIONS
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    full_name  VARCHAR                                 NOT NULL,
    short_name VARCHAR                                 NOT NULL,
    CONSTRAINT pk_organization PRIMARY KEY (id),
    CONSTRAINT UQ_ORGANIZATIONS UNIQUE (full_name, short_name)
);

CREATE TABLE IF NOT EXISTS BRANCHES
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    full_name       VARCHAR                                 NOT NULL,
    short_name      VARCHAR                                 NOT NULL,
    organization_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_branch PRIMARY KEY (id),
    CONSTRAINT UQ_BRANCHES UNIQUE (full_name, short_name),
    CONSTRAINT FK_BRANCHES_ON_ORGANIZATIONS FOREIGN KEY (organization_id) REFERENCES organizations (id)
);

CREATE TABLE IF NOT EXISTS DEPARTMENTS
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    full_name  VARCHAR                                 NOT NULL,
    short_name VARCHAR                                 NOT NULL,
    branch_id  BIGINT                                  NOT NULL,
    CONSTRAINT pk_department PRIMARY KEY (id),
    CONSTRAINT UQ_DEPARTMENTS UNIQUE (full_name, short_name),
    CONSTRAINT FK_DEPARTMENTS_ON_BRANCHES FOREIGN KEY (branch_id) REFERENCES branches (id)
);

CREATE TABLE IF NOT EXISTS HEAT_SUPPLY_SOURCES
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    source        VARCHAR                                 NOT NULL,
    address       VARCHAR                                 NOT NULL,
    department_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_heatSupplySource PRIMARY KEY (id),
    CONSTRAINT UQ_HEAT_SUPPLY_SOURCES UNIQUE (source, address),
    CONSTRAINT FK_HEAT_SUPPLY_SOURCES_ON_DEPARTMENTS FOREIGN KEY (department_id) REFERENCES departments (id)
);

CREATE TABLE IF NOT EXISTS HEAT_SUPPLY_SITES
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    full_description  VARCHAR                                 NOT NULL,
    short_description VARCHAR,
    source_id         BIGINT                                  NOT NULL,
    CONSTRAINT pk_heatSupplySite PRIMARY KEY (id),
    CONSTRAINT FK_HEAT_SUPPLY_SITES_ON_HEAT_SUPPLY_SOURCES FOREIGN KEY (source_id) REFERENCES heat_supply_sources (id)
);

CREATE TABLE IF NOT EXISTS TECHNICAL_DEVICES
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    full_name  VARCHAR                                 NOT NULL,
    short_name VARCHAR                                 NOT NULL,
    site_id    BIGINT                                  NOT NULL,
    CONSTRAINT pk_technicalDevice PRIMARY KEY (id),
    CONSTRAINT UQ_TECHNICAL_DEVICES UNIQUE (full_name, short_name),
    CONSTRAINT FK_TECHNICAL_DEVICES_ON_HEAT_SUPPLY_SITES FOREIGN KEY (site_id) REFERENCES heat_supply_sites (id)
);

CREATE TABLE IF NOT EXISTS EMPLOYEES
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    branch_id     BIGINT                                  NOT NULL,
    department_id BIGINT,
    source_id     BIGINT,
    branch        VARCHAR                                 NOT NULL,
    department    VARCHAR,
    source        VARCHAR,
    initials      VARCHAR                                 NOT NULL,
    full_name     VARCHAR                                 NOT NULL,
    name          VARCHAR                                 NOT NULL,
    patronymic    VARCHAR                                 NOT NULL,
    surname       VARCHAR                                 NOT NULL,
    post          VARCHAR                                 NOT NULL,
    email         VARCHAR                                 NOT NULL,
    CONSTRAINT pk_laboratoryEmployee PRIMARY KEY (id),
    CONSTRAINT UQ_EMPLOYEES UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS EQUIPMENTS_LIBRARY
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    full_name            VARCHAR                                 NOT NULL,
    short_name           VARCHAR                                 NOT NULL,
    volume               INTEGER,
    model                VARCHAR,
    period_stabilization INTEGER,
    diameter             INTEGER,
    length               INTEGER,
    height               INTEGER,
    width                INTEGER,
    dimensions           VARCHAR,
    CONSTRAINT pk_equipmentLibrary PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS ELEMENTS_LIBRARY
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name           VARCHAR                                 NOT NULL,
    equipment_id   BIGINT                                  NOT NULL,
    diameter       INTEGER,
    length         INTEGER,
    height         INTEGER,
    width          INTEGER,
    diameter_size  INTEGER,
    thickness_size DOUBLE PRECISION,
    standard_size  VARCHAR,
    dimensions     VARCHAR,
    CONSTRAINT pk_elementLibrary PRIMARY KEY (id),
    CONSTRAINT FK_ELEMENTS_LIBRARY_ON_EQUIPMENTS_LIBRARY FOREIGN KEY (equipment_id) REFERENCES equipments_library (id)
);

CREATE TABLE IF NOT EXISTS PARTS_ELEMENT_LIBRARY
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    element_id     BIGINT                                  NOT NULL,
    full_name      VARCHAR                                 NOT NULL,
    name           VARCHAR                                 NOT NULL,
    place          VARCHAR,
    diameter       INTEGER,
    length         INTEGER,
    height         INTEGER,
    width          INTEGER,
    diameter_size  INTEGER,
    thickness_size DOUBLE PRECISION,
    standard_size  VARCHAR,
    dimensions     VARCHAR,
    CONSTRAINT pk_partElementLibrary PRIMARY KEY (id),
    CONSTRAINT FK_PARTS_ELEMENT_LIBRARY_ON_ELEMENTS_LIBRARY FOREIGN KEY (element_id) REFERENCES elements_library (id)
);

CREATE TABLE IF NOT EXISTS DEVIATIONS_GEODESY_LIBRARY
(
    id                                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    equipment_library_id              BIGINT                                  NOT NULL,
    heat_carrier                      VARCHAR                                 NOT NULL,
    equipment_condition               VARCHAR                                 NOT NULL,
    volume                            INTEGER                                 NOT NULL,
    acceptable_precipitation          INTEGER,
    max_difference_neighboring_points INTEGER                                 NOT NULL,
    max_difference_diametric_points   INTEGER                                 NOT NULL,
    CONSTRAINT pk_acceptableDeviationsGeodesyLibrary PRIMARY KEY (id),
    CONSTRAINT UQ_DEVIATIONS_GEODESY_LIBRARY UNIQUE (equipment_library_id, heat_carrier, equipment_condition)
);

CREATE TABLE IF NOT EXISTS METAL_HARDNESS_LIBRARY
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    equipment_library_id    BIGINT                                  NOT NULL,
    element_name            VARCHAR                                 NOT NULL,
    element_library_id      BIGINT                                  NOT NULL,
    part_element_library_id BIGINT,
    acceptable_diameter     INTEGER,
    acceptable_thickness    DOUBLE PRECISION                        NOT NULL,
    min_hardness            INTEGER                                 NOT NULL,
    max_hardness            INTEGER,
    measurement_error       FLOAT,
    CONSTRAINT pk_acceptableMetalHardnessLibrary PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS RESIDUAL_THICKNESS_LIBRARY
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    equipment_library_id    BIGINT                                  NOT NULL,
    element_library_id      BIGINT                                  NOT NULL,
    part_element_library_id BIGINT,
    element_name            VARCHAR                                 NOT NULL,
    standard_size           DOUBLE PRECISION                        NOT NULL,
    acceptable_thickness    DOUBLE PRECISION,
    acceptable_percent      INTEGER,
    measurement_error       FLOAT,
    CONSTRAINT pk_acceptableResidualThicknessLibrary PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS DEFECTS_LIBRARY
(
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    equipment                  VARCHAR                                 NOT NULL,
    documentation              VARCHAR                                 NOT NULL,
    name                       VARCHAR                                 NOT NULL,
    measured_parameters        VARCHAR,
    thickness                  VARCHAR,
    total_length               VARCHAR,
    assessment_area            VARCHAR,
    assessment                 VARCHAR,
    quality_assessment         VARCHAR,
    equipment_id               BIGINT                                  NOT NULL,
    documentation_id           BIGINT                                  NOT NULL,
    defects_quantity           INTEGER,
    without_naming_parameter   BOOLEAN,
    assessment_area_mm         DOUBLE PRECISION,
    assessment_area_percentage DOUBLE PRECISION,
    total_length_mm            DOUBLE PRECISION,
    total_length_percentage    DOUBLE PRECISION,
    min_diameter               FLOAT,
    max_diameter               FLOAT,
    min_thickness              FLOAT,
    max_thickness              FLOAT,
    CONSTRAINT pk_defectLibrary PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS REPAIRS_LIBRARY
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                     VARCHAR                                 NOT NULL,
    without_naming_parameter BOOLEAN                                 NOT NULL,
    measured_parameters      VARCHAR,
    CONSTRAINT pk_repairLibrary PRIMARY KEY (id),
    CONSTRAINT UQ_REPAIRS_LIBRARY UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS MEASUREMENT_PARAMETERS_LIBRARY
(
    id                           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                         VARCHAR                                 NOT NULL,
    unit_measurement             VARCHAR                                 NOT NULL,
    calculation_type             VARCHAR                                 NOT NULL,
    calculation                  VARCHAR                                 NOT NULL,
    acceptable_min_mm            FLOAT,
    acceptable_min_percentage    FLOAT,
    acceptable_max_mm            FLOAT,
    acceptable_max_percentage    FLOAT,
    calculate_residual_thickness BOOLEAN,
    defect_id                    BIGINT,
    repair_id                    BIGINT,
    CONSTRAINT pk_measurementParameterLibrary PRIMARY KEY (id),
    CONSTRAINT FK_MEASUREMENT_PARAMETERS_LIBRARY_ON_DEFECTS_LIBRARY
        FOREIGN KEY (defect_id) REFERENCES defects_library (id),
    CONSTRAINT FK_MEASUREMENT_PARAMETERS_LIBRARY_ON_REPAIRS_LIBRARY
        FOREIGN KEY (repair_id) REFERENCES repairs_library (id)
);

CREATE TABLE IF NOT EXISTS REGULATORY_DOCUMENTATION_LIBRARY
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    full_name         VARCHAR                                 NOT NULL,
    document          VARCHAR                                 NOT NULL,
    document_name     VARCHAR                                 NOT NULL,
    type              VARCHAR                                 NOT NULL,
    document_type     VARCHAR                                 NOT NULL,
    status            VARCHAR                                 NOT NULL,
    document_status   VARCHAR                                 NOT NULL,
    area_distribution VARCHAR,
    CONSTRAINT pk_regulatoryDocumentationLibrary PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS DOCUMENTATIONS_EQUIPMENTS
(
    document_id  BIGINT,
    equipment_id BIGINT,
    CONSTRAINT pk_regulatory_documentation_library_equipments_library PRIMARY KEY (document_id, equipment_id)
);

CREATE TABLE IF NOT EXISTS RECOMMENDATION_LIBRARY
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    equipment_library_id BIGINT                                  NOT NULL,
    recommendation       VARCHAR                                 NOT NULL,
    CONSTRAINT pk_recommendationLibrary PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS DIAGNOSIS_LIBRARY
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    diagnosis VARCHAR                                 NOT NULL,
    document  VARCHAR                                 NOT NULL,
    title     VARCHAR                                 NOT NULL,
    CONSTRAINT pk_diagnosisLibrary PRIMARY KEY (id)
);