springdoc:
  swagger-ui:
    path: /swagger-ui-equipment-service.html

server:
  port: 8083

spring:
  application:
    name: equipment-service
  jpa:
    properties:
      hibernate:
        ddl-auto: none
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: mywords
  sql:
    init:
      mode: always

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://eureka-service:8761/eureka
#    healthcheck:
#      enabled: true
#  instance:
#    preferIpAddress: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    healthcheck:
      enabled: true
  instance:
    preferIpAddress: true