springdoc:
  swagger-ui:
    path: /swagger-ui-document-service.html

server:
  port: 8085

spring:
  application:
    name: document-service
  jpa:
    properties:
      hibernate:
        ddl-auto: none
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: mywords
  sql:
    init:
      mode: always

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka
    register-with-eureka: false